language: java
env:
  global:
  - SONATYPE_USERNAME=vpro
  - secure: TdRu39a8x/MiLOsmlMu/cwEFBrDwt2C57HQ/8BEEHqn1kqQ09ANoxfIsMN8BnCyoa0oSTZzgbrCDM+RPOUwR91zm2ShWMsxpgbJ035giSVr2lGnT4dkHtqktmspd9Gw6f0Hoac+7Iji45CRWoegvxuGG9s/GrCnjRxntvmS3jiVilTARjUITOEZCtcutBiDcUJYHa83LmxnkRexhXr+IIyt88l4Mej3s/uXu2eRrE9QszpUzw3CPE9bdqzmY8JgXMOu/R1BzapgTfj6flKEG5Oii52fHXx/t4nNzLOYsfdxJxdyEDqqbxPEx/er4haa+CvfCsy9NpWT/pc13GeozrVyYU0V+pUqoa5wZbxFTSi1nz1khR3NUb2EuPUZBuDWlDVSxCkmgEeUjwxJJfLusVP6dNLSICv7xzPdT64IvmmvpvzTZqcueTxTQ1ezi0wFRHM4nOoZuZv5OEBWxHCUij701dho7+7AwrusJNtWDrVywtZ9YLkREIFn+MntN+mBoOp3Zcuz8MeZ8xWyFE+AKMh4NuNQ1svDjWc8QoUaGuA4ly4Vl9WDBdnBs9HP7FRW1ROGSU2yZ7kMVdqYAByl0ZnX0kx0h5yKiUAIHnSoHx75loXfbPInisW6D/vTcQ5Tap6oUb2wF+vvp0eaKFHlRkkPg1I6FkhYwofHwvY9QNLA=
jdk:
- oraclejdk8
sudo: false
script: mvn --fail-never -T 1C -Pdeploy,ossrh -DskipITs=false test integration-test
  deploy --settings .travis-settings.xml -Dgpg.skip=true
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- mkdir $HOME/conf
- openssl aes-256-cbc -K $encrypted_586f6f68bf53_key -iv $encrypted_586f6f68bf53_iv
  -in .travis/apiclient.properties.enc -out $HOME/conf/apiclient.properties -d
